#:schema node_modules/wrangler/config-schema.json
name = "dyzh5-worker"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "89df8a1d41d74d949485d0d3ca314e47" }
]
